<?php
namespace App\Console\Commands;

use App\Models\AddOn;
use App\Models\Admin;
use App\Models\Category;
use App\Models\CategoryFeature;
use App\Models\CategoryFeatureCategory;
use App\Models\CategoryFeatureValue;
use App\Models\City;
use App\Models\CommentResponse;
use App\Models\Gallery;
use App\Models\Message;
use App\Models\Notice;
use App\Models\Order;
use App\Models\Setting;
use App\Models\State;
use App\Models\Tariff;
use App\Models\Ticket;
use App\Models\TicketFile;
use App\Models\TicketResponse;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\DB;
use App;

class Infrastructure extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = "infrastructure:build";

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = "create provinces and cities";

    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Execute the console command.
     *
     * @return mixed
     */
    public function handle()
    {

        if (State::count() == 0) {
            $this->cityAndProvince();
        }
    }

    public function cityAndProvince()
    {
        DB::table('states')->insert(
            [
                ['id' => 1, 'name' => 'آذربایجان شرقی'],
                ['id' => 2, 'name' => 'آذربایجان غربی'],
                ['id' => 3, 'name' => 'اردبیل'],
                ['id' => 4, 'name' => 'اصفهان'],
                ['id' => 5, 'name' => 'البرز'],
                ['id' => 6, 'name' => 'ایلام'],
                ['id' => 7, 'name' => 'بوشهر'],
                ['id' => 8, 'name' => 'تهران'],
                ['id' => 9, 'name' => 'چهارمحال بختیاری'],
                ['id' => 10, 'name' => 'خراسان جنوبی'],
                ['id' => 11, 'name' => 'خراسان رضوی'],
                ['id' => 12, 'name' => 'خراسان شمالی'],
                ['id' => 13, 'name' => 'خوزستان'],
                ['id' => 14, 'name' => 'زنجان'],
                ['id' => 15, 'name' => 'سمنان'],
                ['id' => 16, 'name' => 'سیستان و بلوچستان'],
                ['id' => 17, 'name' => 'فارس'],
                ['id' => 18, 'name' => 'قزوین'],
                ['id' => 19, 'name' => 'قم'],
                ['id' => 20, 'name' => 'کردستان'],
                ['id' => 21, 'name' => 'کرمان'],
                ['id' => 22, 'name' => 'کرمانشاه'],
                ['id' => 23, 'name' => 'کهکیلویه و بویراحمد'],
                ['id' => 24, 'name' => 'گلستان'],
                ['id' => 25, 'name' => 'گیلان'],
                ['id' => 26, 'name' => 'لرستان'],
                ['id' => 27, 'name' => 'مازندران'],
                ['id' => 28, 'name' => 'مرکزی'],
                ['id' => 29, 'name' => 'هرمزگان'],
                ['id' => 30, 'name' => 'همدان'],
                ['id' => 31, 'name' => 'یزد']
            ]
        );
        DB::table('cities')->insert(
            [
                ['id' => 1, 'state_id' => 1, 'name' => 'تبریز'],
                ['id' => 2, 'state_id' => 1, 'name' => 'کندوان'],
                ['id' => 3, 'state_id' => 1, 'name' => 'بندر شرفخانه'],
                ['id' => 4, 'state_id' => 1, 'name' => 'مراغه'],
                ['id' => 5, 'state_id' => 1, 'name' => 'میانه'],
                ['id' => 6, 'state_id' => 1, 'name' => 'شبستر'],
                ['id' => 7, 'state_id' => 1, 'name' => 'مرند'],
                ['id' => 8, 'state_id' => 1, 'name' => 'جلفا'],
                ['id' => 9, 'state_id' => 1, 'name' => 'سراب'],
                ['id' => 10, 'state_id' =>  1,  'name' => 'هادیشهر'],
                ['id' => 11, 'state_id' =>  1,  'name' => 'بناب'],
                ['id' => 12, 'state_id' =>  1,  'name' => 'کلیبر'],
                ['id' => 13, 'state_id' =>  1,  'name' => 'تسوج'],
                ['id' => 14, 'state_id' =>  1,  'name' => 'اهر'],
                ['id' => 15, 'state_id' =>  1,  'name' => 'هریس'],
                ['id' => 16, 'state_id' =>  1,  'name' => 'عجبشیر'],
                ['id' => 17, 'state_id' =>  1,  'name' => 'هشترود'],
                ['id' => 18, 'state_id' =>  1,  'name' => 'ملکان'],
                ['id' => 19, 'state_id' =>  1,  'name' => 'بستان آباد'],
                ['id' => 20, 'state_id' =>  1,  'name' => 'ورزقان'],
                ['id' => 21, 'state_id' =>  1,  'name' => 'اسکو'],
                ['id' => 22, 'state_id' =>  1,  'name' => 'آذر شهر'],
                ['id' => 23, 'state_id' =>  1,  'name' => 'قره آغاج'],
                ['id' => 24, 'state_id' =>  1,  'name' => 'ممقان'],
                ['id' => 25, 'state_id' =>  1,  'name' => 'صوفیان'],
                ['id' => 26, 'state_id' =>  1,  'name' => 'ایلخچی'],
                ['id' => 27, 'state_id' =>  1,  'name' => 'خسروشهر'],
                ['id' => 28, 'state_id' =>  1,  'name' => 'باسمنج'],
                ['id' => 29, 'state_id' =>  1,  'name' => 'سهند'],
                ['id' => 30, 'state_id' =>  2,  'name' => 'ارومیه'],
                ['id' => 31, 'state_id' =>  2,  'name' => 'نقده'],
                ['id' => 32, 'state_id' =>  2,  'name' => 'ماکو'],
                ['id' => 33, 'state_id' =>  2,  'name' => 'تکاب'],
                ['id' => 34, 'state_id' =>  2,  'name' => 'خوی'],
                ['id' => 35, 'state_id' =>  2,  'name' => 'مهاباد'],
                ['id' => 36, 'state_id' =>  2,  'name' => 'سر دشت'],
                ['id' => 37, 'state_id' =>  2,  'name' => 'چالدران'],
                ['id' => 38, 'state_id' =>  2,  'name' => 'بوکان'],
                ['id' => 39, 'state_id' =>  2,  'name' => 'میاندوآب'],
                ['id' => 40, 'state_id' =>  2,  'name' => 'سلماس'],
                ['id' => 41, 'state_id' =>  2,  'name' => 'شاهین دژ'],
                ['id' => 42, 'state_id' =>  2,  'name' => 'پیرانشهر'],
                ['id' => 43, 'state_id' =>  2,  'name' => 'سیه چشمه'],
                ['id' => 44, 'state_id' =>  2,  'name' => 'اشنویه'],
                ['id' => 45, 'state_id' =>  2,  'name' => 'چایپاره'],
                ['id' => 46, 'state_id' =>  2,  'name' => 'پلدشت'],
                ['id' => 47, 'state_id' =>  2,  'name' => 'شوط'],
                ['id' => 48, 'state_id' =>  3,  'name' => 'اردبیل'],
                ['id' => 49, 'state_id' =>  3,  'name' => 'سرعین'],
                ['id' => 50, 'state_id' =>  3,  'name' => 'بیله سوار'],
                ['id' => 51, 'state_id' =>  3,  'name' => 'پارس آباد'],
                ['id' => 52, 'state_id' =>  3,  'name' => 'خلخال'],
                ['id' => 53, 'state_id' =>  3,  'name' => 'مشگین شهر'],
                ['id' => 54, 'state_id' =>  3,  'name' => 'مغان'],
                ['id' => 55, 'state_id' =>  3,  'name' => 'نمین'],
                ['id' => 56, 'state_id' =>  3,  'name' => 'نیر'],
                ['id' => 57, 'state_id' =>  3,  'name' => 'کوثر'],
                ['id' => 58, 'state_id' =>  3,  'name' => 'کیوی'],
                ['id' => 59, 'state_id' =>  3,  'name' => 'گرمی'],
                ['id' => 60, 'state_id' =>  4,  'name' => 'اصفهان'],
                ['id' => 61, 'state_id' =>  4,  'name' => 'فریدن'],
                ['id' => 62, 'state_id' =>  4,  'name' => 'فریدون شهر'],
                ['id' => 63, 'state_id' =>  4,  'name' => 'فلاورجان'],
                ['id' => 64, 'state_id' =>  4,  'name' => 'گلپایگان'],
                ['id' => 65, 'state_id' =>  4,  'name' => 'دهاقان'],
                ['id' => 66, 'state_id' =>  4,  'name' => 'نطنز'],
                ['id' => 67, 'state_id' =>  4,  'name' => 'نایین'],
                ['id' => 68, 'state_id' =>  4,  'name' => 'تیران'],
                ['id' => 69, 'state_id' =>  4,  'name' => 'کاشان'],
                ['id' => 70, 'state_id' =>  4,  'name' => 'فولاد شهر'],
                ['id' => 71, 'state_id' =>  4,  'name' => 'اردستان'],
                ['id' => 72, 'state_id' =>  4,  'name' => 'سمیرم'],
                ['id' => 73, 'state_id' =>  4,  'name' => 'درچه'],
                ['id' => 74, 'state_id' =>  4,  'name' => 'کوهپایه'],
                ['id' => 75, 'state_id' =>  4,  'name' => 'مبارکه'],
                ['id' => 76, 'state_id' =>  4,  'name' => 'شهرضا'],
                ['id' => 77, 'state_id' =>  4,  'name' => 'خمینی شهر'],
                ['id' => 78, 'state_id' =>  4,  'name' => 'شاهین شهر'],
                ['id' => 79, 'state_id' =>  4,  'name' => 'نجف آباد'],
                ['id' => 80, 'state_id' =>  4,  'name' => 'دولت آباد'],
                ['id' => 81, 'state_id' =>  4,  'name' => 'زرین شهر'],
                ['id' => 82, 'state_id' =>  4,  'name' => 'آران و بیدگل'],
                ['id' => 83, 'state_id' =>  4,  'name' => 'باغ بهادران'],
                ['id' => 84, 'state_id' =>  4,  'name' => 'خوانسار'],
                ['id' => 85, 'state_id' =>  4,  'name' => 'مهردشت'],
                ['id' => 86, 'state_id' =>  4,  'name' => 'علویجه'],
                ['id' => 87, 'state_id' =>  4,  'name' => 'عسگران'],
                ['id' => 88, 'state_id' =>  4,  'name' => 'نهضت آباد'],
                ['id' => 89, 'state_id' =>  4,  'name' => 'حاجی آباد'],
                ['id' => 90, 'state_id' =>  4,  'name' => 'تودشک'],
                ['id' => 91, 'state_id' =>  4,  'name' => 'ورزنه'],
                ['id' => 92, 'state_id' =>  6,  'name' => 'ایلام'],
                ['id' => 93, 'state_id' =>  6,  'name' => 'مهران'],
                ['id' => 94, 'state_id' =>  6,  'name' => 'دهلران'],
                ['id' => 95, 'state_id' =>  6,  'name' => 'آبدانان'],
                ['id' => 96, 'state_id' =>  6,  'name' => 'شیروان چرداول'],
                ['id' => 97, 'state_id' =>  6,  'name' => 'دره شهر'],
                ['id' => 98, 'state_id' =>  6,  'name' => 'ایوان'],
                ['id' => 99, 'state_id' =>  6,  'name' => 'سرابله'],
                ['id' => 100, 'state_id' =>  7,  'name' => 'بوشهر'],
                ['id' => 101, 'state_id' =>  7,  'name' => 'تنگستان'],
                ['id' => 102, 'state_id' =>  7,  'name' => 'دشتستان'],
                ['id' => 103, 'state_id' =>  7,  'name' => 'دیر'],
                ['id' => 104, 'state_id' =>  7,  'name' => 'دیلم'],
                ['id' => 105, 'state_id' =>  7,  'name' => 'کنگان'],
                ['id' => 106, 'state_id' =>  7,  'name' => 'گناوه'],
                ['id' => 107, 'state_id' =>  7,  'name' => 'ریشهر'],
                ['id' => 108, 'state_id' =>  7,  'name' => 'دشتی'],
                ['id' => 109, 'state_id' =>  7,  'name' => 'خورموج'],
                ['id' => 110, 'state_id' =>  7,  'name' => 'اهرم'],
                ['id' => 111, 'state_id' =>  7,  'name' => 'برازجان'],
                ['id' => 112, 'state_id' =>  7,  'name' => 'خارک'],
                ['id' => 113, 'state_id' =>  7,  'name' => 'جم'],
                ['id' => 114, 'state_id' =>  7,  'name' => 'کاکی'],
                ['id' => 115, 'state_id' =>  7,  'name' => 'عسلویه'],
                ['id' => 116, 'state_id' =>  7,  'name' => 'بردخون'],
                ['id' => 117, 'state_id' =>  8,  'name' => 'تهران'],
                ['id' => 118, 'state_id' =>  8,  'name' => 'ورامین'],
                ['id' => 119, 'state_id' =>  8,  'name' => 'فیروزکوه'],
                ['id' => 120, 'state_id' =>  8,  'name' => 'ری'],
                ['id' => 121, 'state_id' =>  8,  'name' => 'دماوند'],
                ['id' => 122, 'state_id' =>  8,  'name' => 'اسلامشهر'],
                ['id' => 123, 'state_id' =>  8,  'name' => 'رودهن'],
                ['id' => 124, 'state_id' =>  8,  'name' => 'لواسان'],
                ['id' => 125, 'state_id' =>  8,  'name' => 'بومهن'],
                ['id' => 126, 'state_id' =>  8,  'name' => 'تجریش'],
                ['id' => 127, 'state_id' =>  8,  'name' => 'فشم'],
                ['id' => 128, 'state_id' =>  8,  'name' => 'کهریزک'],
                ['id' => 129, 'state_id' =>  8,  'name' => 'پاکدشت'],
                ['id' => 130, 'state_id' =>  8,  'name' => 'چهاردانگه'],
                ['id' => 131, 'state_id' =>  8,  'name' => 'شریف آباد'],
                ['id' => 132, 'state_id' =>  8,  'name' => 'قرچک'],
                ['id' => 133, 'state_id' =>  8,  'name' => 'باقرشهر'],
                ['id' => 134, 'state_id' =>  8,  'name' => 'شهریار'],
                ['id' => 135, 'state_id' =>  8,  'name' => 'رباط کریم'],
                ['id' => 136, 'state_id' =>  8,  'name' => 'قدس'],
                ['id' => 137, 'state_id' =>  8,  'name' => 'ملارد'],
                ['id' => 138, 'state_id' =>  9,  'name' => 'شهرکرد'],
                ['id' => 139, 'state_id' =>  9,  'name' => 'فارسان'],
                ['id' => 140, 'state_id' =>  9,  'name' => 'بروجن'],
                ['id' => 141, 'state_id' =>  9,  'name' => 'چلگرد'],
                ['id' => 142, 'state_id' =>  9,  'name' => 'اردل'],
                ['id' => 143, 'state_id' =>  9,  'name' => 'لردگان'],
                ['id' => 144, 'state_id' =>  9,  'name' => 'سامان'],
                ['id' => 145, 'state_id' =>  10, 'name' => 'قائن'],
                ['id' => 146, 'state_id' =>  10, 'name' => 'فردوس'],
                ['id' => 147, 'state_id' =>  10, 'name' => 'بیرجند'],
                ['id' => 148, 'state_id' =>  10, 'name' => 'نهبندان'],
                ['id' => 149, 'state_id' =>  10, 'name' => 'سربیشه'],
                ['id' => 150, 'state_id' =>  10, 'name' => 'طبس مسینا'],
                ['id' => 151, 'state_id' =>  10, 'name' => 'قهستان'],
                ['id' => 152, 'state_id' =>  10, 'name' => 'درمیان'],
                ['id' => 153, 'state_id' =>  11, 'name' => 'مشهد'],
                ['id' => 154, 'state_id' =>  11, 'name' => 'نیشابور'],
                ['id' => 155, 'state_id' =>  11, 'name' => 'سبزوار'],
                ['id' => 156, 'state_id' =>  11, 'name' => 'کاشمر'],
                ['id' => 157, 'state_id' =>  11, 'name' => 'گناباد'],
                ['id' => 158, 'state_id' =>  11, 'name' => 'طبس'],
                ['id' => 159, 'state_id' =>  11, 'name' => 'تربت حیدریه'],
                ['id' => 160, 'state_id' =>  11, 'name' => 'خواف'],
                ['id' => 161, 'state_id' =>  11, 'name' => 'تربت جام'],
                ['id' => 162, 'state_id' =>  11, 'name' => 'تایباد'],
                ['id' => 163, 'state_id' =>  11, 'name' => 'قوچان'],
                ['id' => 164, 'state_id' =>  11, 'name' => 'سرخس'],
                ['id' => 165, 'state_id' =>  11, 'name' => 'بردسکن'],
                ['id' => 166, 'state_id' =>  11, 'name' => 'فریمان'],
                ['id' => 167, 'state_id' =>  11, 'name' => 'چناران'],
                ['id' => 168, 'state_id' =>  11, 'name' => 'درگز'],
                ['id' => 169, 'state_id' =>  11, 'name' => 'کلات'],
                ['id' => 170, 'state_id' =>  11, 'name' => 'طرقبه'],
                ['id' => 171, 'state_id' =>  11, 'name' => 'سر ولایت'],
                ['id' => 172, 'state_id' =>  12, 'name' => 'بجنورد'],
                ['id' => 173, 'state_id' =>  12, 'name' => 'اسفراین'],
                ['id' => 174, 'state_id' =>  12, 'name' => 'جاجرم'],
                ['id' => 175, 'state_id' =>  12, 'name' => 'شیروان'],
                ['id' => 176, 'state_id' =>  12, 'name' => 'آشخانه'],
                ['id' => 177, 'state_id' =>  12, 'name' => 'گرمه'],
                ['id' => 178, 'state_id' =>  12, 'name' => 'ساروج'],
                ['id' => 179, 'state_id' =>  13, 'name' => 'اهواز'],
                ['id' => 180, 'state_id' =>  13, 'name' => 'ایرانشهر'],
                ['id' => 181, 'state_id' =>  13, 'name' => 'شوش'],
                ['id' => 182, 'state_id' =>  13, 'name' => 'آبادان'],
                ['id' => 183, 'state_id' =>  13, 'name' => 'خرمشهر'],
                ['id' => 184, 'state_id' =>  13, 'name' => 'مسجد سلیمان'],
                ['id' => 185, 'state_id' =>  13, 'name' => 'ایذه'],
                ['id' => 186, 'state_id' =>  13, 'name' => 'شوشتر'],
                ['id' => 187, 'state_id' =>  13, 'name' => 'اندیمشک'],
                ['id' => 188, 'state_id' =>  13, 'name' => 'سوسنگرد'],
                ['id' => 189, 'state_id' =>  13, 'name' => 'هویزه'],
                ['id' => 190, 'state_id' =>  13, 'name' => 'دزفول'],
                ['id' => 191, 'state_id' =>  13, 'name' => 'شادگان'],
                ['id' => 192, 'state_id' =>  13, 'name' => 'بندر ماهشهر'],
                ['id' => 193, 'state_id' =>  13, 'name' => 'بندر امام خمینی'],
                ['id' => 194, 'state_id' =>  13, 'name' => 'امیدیه'],
                ['id' => 195, 'state_id' =>  13, 'name' => 'بهبهان'],
                ['id' => 196, 'state_id' =>  13, 'name' => 'رامهرمز'],
                ['id' => 197, 'state_id' =>  13, 'name' => 'باغ ملک'],
                ['id' => 198, 'state_id' =>  13, 'name' => 'هندیجان'],
                ['id' => 199, 'state_id' =>  13, 'name' => 'لالی'],
                ['id' => 200, 'state_id' =>  13, 'name' => 'رامشیر'],
                ['id' => 201, 'state_id' =>  13, 'name' => 'حمیدیه'],
                ['id' => 202, 'state_id' =>  13, 'name' => 'دغاغله'],
                ['id' => 203, 'state_id' =>  13, 'name' => 'ملاثانی'],
                ['id' => 204, 'state_id' =>  13, 'name' => 'شادگان'],
                ['id' => 205, 'state_id' =>  13, 'name' => 'ویسی'],
                ['id' => 206, 'state_id' =>  14, 'name' => 'زنجان'],
                ['id' => 207, 'state_id' =>  14, 'name' => 'ابهر'],
                ['id' => 208, 'state_id' =>  14, 'name' => 'خدابنده'],
                ['id' => 209, 'state_id' =>  14, 'name' => 'طارم'],
                ['id' => 210, 'state_id' =>  14, 'name' => 'ماهنشان'],
                ['id' => 211, 'state_id' =>  14, 'name' => 'خرمدره'],
                ['id' => 212, 'state_id' =>  14, 'name' => 'ایجرود'],
                ['id' => 213, 'state_id' =>  14, 'name' => 'زرین آباد'],
                ['id' => 214, 'state_id' =>  14, 'name' => 'آب بر'],
                ['id' => 215, 'state_id' =>  14, 'name' => 'قیدار'],
                ['id' => 216, 'state_id' =>  15, 'name' => 'سمنان'],
                ['id' => 217, 'state_id' =>  15, 'name' => 'شاهرود'],
                ['id' => 218, 'state_id' =>  15, 'name' => 'گرمسار'],
                ['id' => 219, 'state_id' =>  15, 'name' => 'ایوانکی'],
                ['id' => 220, 'state_id' =>  15, 'name' => 'دامغان'],
                ['id' => 221, 'state_id' =>  15, 'name' => 'بسطام'],
                ['id' => 222, 'state_id' =>  16, 'name' => 'زاهدان'],
                ['id' => 223, 'state_id' =>  16, 'name' => 'چابهار'],
                ['id' => 224, 'state_id' =>  16, 'name' => 'خاش'],
                ['id' => 225, 'state_id' =>  16, 'name' => 'سراوان'],
                ['id' => 226, 'state_id' =>  16, 'name' => 'زابل'],
                ['id' => 227, 'state_id' =>  16, 'name' => 'سرباز'],
                ['id' => 228, 'state_id' =>  16, 'name' => 'نیکشهر'],
                ['id' => 229, 'state_id' =>  16, 'name' => 'ایرانشهر'],
                ['id' => 230, 'state_id' =>  16, 'name' => 'راسک'],
                ['id' => 231, 'state_id' =>  16, 'name' => 'میرجاوه'],
                ['id' => 232, 'state_id' =>  17, 'name' => 'شیراز'],
                ['id' => 233, 'state_id' =>  17, 'name' => 'اقلید'],
                ['id' => 234, 'state_id' =>  17, 'name' => 'داراب'],
                ['id' => 235, 'state_id' =>  17, 'name' => 'فسا'],
                ['id' => 236, 'state_id' =>  17, 'name' => 'مرودشت'],
                ['id' => 237, 'state_id' =>  17, 'name' => 'خرم بید'],
                ['id' => 238, 'state_id' =>  17, 'name' => 'آباده'],
                ['id' => 239, 'state_id' =>  17, 'name' => 'کازرون'],
                ['id' => 240, 'state_id' =>  17, 'name' => 'ممسنی'],
                ['id' => 241, 'state_id' =>  17, 'name' => 'سپیدان'],
                ['id' => 242, 'state_id' =>  17, 'name' => 'لار'],
                ['id' => 243, 'state_id' =>  17, 'name' => 'فیروز آباد'],
                ['id' => 244, 'state_id' =>  17, 'name' => 'جهرم'],
                ['id' => 245, 'state_id' =>  17, 'name' => 'نی ریز'],
                ['id' => 246, 'state_id' =>  17, 'name' => 'استهبان'],
                ['id' => 247, 'state_id' =>  17, 'name' => 'لامرد'],
                ['id' => 248, 'state_id' =>  17, 'name' => 'مهر'],
                ['id' => 249, 'state_id' =>  17, 'name' => 'حاجی آباد'],
                ['id' => 250, 'state_id' =>  17, 'name' => 'نورآباد'],
                ['id' => 251, 'state_id' =>  17, 'name' => 'اردکان'],
                ['id' => 252, 'state_id' =>  17, 'name' => 'صفاشهر'],
                ['id' => 253, 'state_id' =>  17, 'name' => 'ارسنجان'],
                ['id' => 254, 'state_id' =>  17, 'name' => 'قیروکارزین'],
                ['id' => 255, 'state_id' =>  17, 'name' => 'سوریان'],
                ['id' => 256, 'state_id' =>  17, 'name' => 'فراشبند'],
                ['id' => 257, 'state_id' =>  17, 'name' => 'سروستان'],
                ['id' => 258, 'state_id' =>  17, 'name' => 'ارژن'],
                ['id' => 259, 'state_id' =>  17, 'name' => 'گویم'],
                ['id' => 260, 'state_id' =>  17, 'name' => 'داریون'],
                ['id' => 261, 'state_id' =>  17, 'name' => 'زرقان'],
                ['id' => 262, 'state_id' =>  17, 'name' => 'خان زنیان'],
                ['id' => 263, 'state_id' =>  17, 'name' => 'کوار'],
                ['id' => 264, 'state_id' =>  17, 'name' => 'ده بید'],
                ['id' => 265, 'state_id' =>  17, 'name' => 'باب انار/خفر'],
                ['id' => 266, 'state_id' =>  17, 'name' => 'بوانات'],
                ['id' => 267, 'state_id' =>  17, 'name' => 'خرامه'],
                ['id' => 268, 'state_id' =>  17, 'name' => 'خنج'],
                ['id' => 269, 'state_id' =>  17, 'name' => 'سیاخ دارنگون'],
                ['id' => 270, 'state_id' =>  18, 'name' => 'قزوین'],
                ['id' => 271, 'state_id' =>  18, 'name' => 'تاکستان'],
                ['id' => 272, 'state_id' =>  18, 'name' => 'آبیک'],
                ['id' => 273, 'state_id' =>  18, 'name' => 'بوئین زهرا'],
                ['id' => 274, 'state_id' =>  19, 'name' => 'قم'],
                ['id' => 275, 'state_id' =>  5,  'name' => 'طالقان'],
                ['id' => 276, 'state_id' =>  5,  'name' => 'نظرآباد'],
                ['id' => 277, 'state_id' =>  5,  'name' => 'اشتهارد'],
                ['id' => 278, 'state_id' =>  5,  'name' => 'هشتگرد'],
                ['id' => 279, 'state_id' =>  5,  'name' => 'کن'],
                ['id' => 280, 'state_id' =>  5,  'name' => 'آسارا'],
                ['id' => 281, 'state_id' =>  5,  'name' => 'شهرک گلستان'],
                ['id' => 282, 'state_id' =>  5,  'name' => 'اندیشه'],
                ['id' => 283, 'state_id' =>  5,  'name' => 'کرج'],
                ['id' => 284, 'state_id' =>  5,  'name' => 'نظر آباد'],
                ['id' => 285, 'state_id' =>  5,  'name' => 'گوهردشت'],
                ['id' => 286, 'state_id' =>  5,  'name' => 'ماهدشت'],
                ['id' => 287, 'state_id' =>  5,  'name' => 'مشکین دشت'],
                ['id' => 288, 'state_id' =>  20, 'name' => 'سنندج'],
                ['id' => 289, 'state_id' =>  20, 'name' => 'دیواندره'],
                ['id' => 290, 'state_id' =>  20, 'name' => 'بانه'],
                ['id' => 291, 'state_id' =>  20, 'name' => 'بیجار'],
                ['id' => 292, 'state_id' =>  20, 'name' => 'سقز'],
                ['id' => 293, 'state_id' =>  20, 'name' => 'کامیاران'],
                ['id' => 294, 'state_id' =>  20, 'name' => 'قروه'],
                ['id' => 295, 'state_id' =>  20, 'name' => 'مریوان'],
                ['id' => 296, 'state_id' =>  20, 'name' => 'صلوات آباد'],
                ['id' => 297, 'state_id' =>  20, 'name' => 'حسن آباد'],
                ['id' => 298, 'state_id' =>  21, 'name' => 'کرمان'],
                ['id' => 299, 'state_id' =>  21, 'name' => 'راور'],
                ['id' => 300, 'state_id' =>  21, 'name' => 'بابک'],
                ['id' => 301, 'state_id' =>  21, 'name' => 'انار'],
                ['id' => 302, 'state_id' =>  21, 'name' => 'کوهبنان'],
                ['id' => 303, 'state_id' =>  21, 'name' => 'رفسنجان'],
                ['id' => 304, 'state_id' =>  21, 'name' => 'بافت'],
                ['id' => 305, 'state_id' =>  21, 'name' => 'سیرجان'],
                ['id' => 306, 'state_id' =>  21, 'name' => 'کهنوج'],
                ['id' => 307, 'state_id' =>  21, 'name' => 'زرند'],
                ['id' => 308, 'state_id' =>  21, 'name' => 'بم'],
                ['id' => 309, 'state_id' =>  21, 'name' => 'جیرفت'],
                ['id' => 310, 'state_id' =>  21, 'name' => 'بردسیر'],
                ['id' => 311, 'state_id' =>  22, 'name' => 'کرمانشاه'],
                ['id' => 312, 'state_id' =>  22, 'name' => 'اسلام آباد غرب'],
                ['id' => 313, 'state_id' =>  22, 'name' => 'سر پل ذهاب'],
                ['id' => 314, 'state_id' =>  22, 'name' => 'کنگاور'],
                ['id' => 315, 'state_id' =>  22, 'name' => 'سنقر'],
                ['id' => 316, 'state_id' =>  22, 'name' => 'قصر شیرین'],
                ['id' => 317, 'state_id' =>  22, 'name' => 'گیلان غرب'],
                ['id' => 318, 'state_id' =>  22, 'name' => 'هرسین'],
                ['id' => 319, 'state_id' =>  22, 'name' => 'صحنه'],
                ['id' => 320, 'state_id' =>  22, 'name' => 'پاوه'],
                ['id' => 321, 'state_id' =>  22, 'name' => 'جوانرود'],
                ['id' => 322, 'state_id' =>  22, 'name' => 'شاهو'],
                ['id' => 323, 'state_id' =>  23, 'name' => 'یاسوج'],
                ['id' => 324, 'state_id' =>  23, 'name' => 'گچساران'],
                ['id' => 325, 'state_id' =>  23, 'name' => 'دنا'],
                ['id' => 326, 'state_id' =>  23, 'name' => 'دوگنبدان'],
                ['id' => 327, 'state_id' =>  23, 'name' => 'سی سخت'],
                ['id' => 328, 'state_id' =>  23, 'name' => 'دهدشت'],
                ['id' => 329, 'state_id' =>  23, 'name' => 'لیکک'],
                ['id' => 330, 'state_id' =>  24, 'name' => 'گرگان'],
                ['id' => 331, 'state_id' =>  24, 'name' => 'آق قلا'],
                ['id' => 332, 'state_id' =>  24, 'name' => 'گنبد کاووس'],
                ['id' => 333, 'state_id' =>  24, 'name' => 'علی آباد کتول'],
                ['id' => 334, 'state_id' =>  24, 'name' => 'مینو دشت'],
                ['id' => 335, 'state_id' =>  24, 'name' => 'ترکمن'],
                ['id' => 336, 'state_id' =>  24, 'name' => 'کردکوی'],
                ['id' => 337, 'state_id' =>  24, 'name' => 'بندر گز'],
                ['id' => 338, 'state_id' =>  24, 'name' => 'کلاله'],
                ['id' => 339, 'state_id' =>  24, 'name' => 'آزاد شهر'],
                ['id' => 340, 'state_id' =>  24, 'name' => 'رامیان'],
                ['id' => 341, 'state_id' =>  25, 'name' => 'رشت'],
                ['id' => 342, 'state_id' =>  25, 'name' => 'منجیل'],
                ['id' => 343, 'state_id' =>  25, 'name' => 'لنگرود'],
                ['id' => 344, 'state_id' =>  25, 'name' => 'رود سر'],
                ['id' => 345, 'state_id' =>  25, 'name' => 'تالش'],
                ['id' => 346, 'state_id' =>  25, 'name' => 'آستارا'],
                ['id' => 347, 'state_id' =>  25, 'name' => 'ماسوله'],
                ['id' => 348, 'state_id' =>  25, 'name' => 'آستانه اشرفیه'],
                ['id' => 349, 'state_id' =>  25, 'name' => 'رودبار'],
                ['id' => 350, 'state_id' =>  25, 'name' => 'فومن'],
                ['id' => 351, 'state_id' =>  25, 'name' => 'صومعه سرا'],
                ['id' => 352, 'state_id' =>  25, 'name' => 'بندرانزلی'],
                ['id' => 353, 'state_id' =>  25, 'name' => 'کلاچای'],
                ['id' => 354, 'state_id' =>  25, 'name' => 'هشتپر'],
                ['id' => 355, 'state_id' =>  25, 'name' => 'رضوان شهر'],
                ['id' => 356, 'state_id' =>  25, 'name' => 'ماسال'],
                ['id' => 357, 'state_id' =>  25, 'name' => 'شفت'],
                ['id' => 358, 'state_id' =>  25, 'name' => 'سیاهکل'],
                ['id' => 359, 'state_id' =>  25, 'name' => 'املش'],
                ['id' => 360, 'state_id' =>  25, 'name' => 'لاهیجان'],
                ['id' => 361, 'state_id' =>  25, 'name' => 'خشک بیجار'],
                ['id' => 362, 'state_id' =>  25, 'name' => 'خمام'],
                ['id' => 363, 'state_id' =>  25, 'name' => 'لشت نشا'],
                ['id' => 364, 'state_id' =>  25, 'name' => 'بندر کیاشهر'],
                ['id' => 365, 'state_id' =>  26, 'name' => 'خرم آباد'],
                ['id' => 366, 'state_id' =>  26, 'name' => 'ماهشهر'],
                ['id' => 367, 'state_id' =>  26, 'name' => 'دزفول'],
                ['id' => 368, 'state_id' =>  26, 'name' => 'بروجرد'],
                ['id' => 369, 'state_id' =>  26, 'name' => 'دورود'],
                ['id' => 370, 'state_id' =>  26, 'name' => 'الیگودرز'],
                ['id' => 371, 'state_id' =>  26, 'name' => 'ازنا'],
                ['id' => 372, 'state_id' =>  26, 'name' => 'نور آباد'],
                ['id' => 373, 'state_id' =>  26, 'name' => 'کوهدشت'],
                ['id' => 374, 'state_id' =>  26, 'name' => 'الشتر'],
                ['id' => 375, 'state_id' =>  26, 'name' => 'پلدختر'],
                ['id' => 376, 'state_id' =>  27, 'name' => 'ساری'],
                ['id' => 377, 'state_id' =>  27, 'name' => 'آمل'],
                ['id' => 378, 'state_id' =>  27, 'name' => 'بابل'],
                ['id' => 379, 'state_id' =>  27, 'name' => 'بابلسر'],
                ['id' => 380, 'state_id' =>  27, 'name' => 'بهشهر'],
                ['id' => 381, 'state_id' =>  27, 'name' => 'تنکابن'],
                ['id' => 382, 'state_id' =>  27, 'name' => 'جویبار'],
                ['id' => 383, 'state_id' =>  27, 'name' => 'چالوس'],
                ['id' => 384, 'state_id' =>  27, 'name' => 'رامسر'],
                ['id' => 385, 'state_id' =>  27, 'name' => 'سواد کوه'],
                ['id' => 386, 'state_id' =>  27, 'name' => 'قائم شهر'],
                ['id' => 387, 'state_id' =>  27, 'name' => 'نکا'],
                ['id' => 388, 'state_id' =>  27, 'name' => 'نور'],
                ['id' => 389, 'state_id' =>  27, 'name' => 'بلده'],
                ['id' => 390, 'state_id' =>  27, 'name' => 'نوشهر'],
                ['id' => 391, 'state_id' =>  27, 'name' => 'پل سفید'],
                ['id' => 392, 'state_id' =>  27, 'name' => 'محمود آباد'],
                ['id' => 393, 'state_id' =>  27, 'name' => 'فریدون کنار'],
                ['id' => 394, 'state_id' =>  28, 'name' => 'اراک'],
                ['id' => 395, 'state_id' =>  28, 'name' => 'آشتیان'],
                ['id' => 396, 'state_id' =>  28, 'name' => 'تفرش'],
                ['id' => 397, 'state_id' =>  28, 'name' => 'خمین'],
                ['id' => 398, 'state_id' =>  28, 'name' => 'دلیجان'],
                ['id' => 399, 'state_id' =>  28, 'name' => 'ساوه'],
                ['id' => 400, 'state_id' =>  28, 'name' => 'سربند'],
                ['id' => 401, 'state_id' =>  28, 'name' => 'محلات'],
                ['id' => 402, 'state_id' =>  28, 'name' => 'شازند'],
                ['id' => 403, 'state_id' =>  29, 'name' => 'بندرعباس'],
                ['id' => 404, 'state_id' =>  29, 'name' => 'قشم'],
                ['id' => 405, 'state_id' =>  29, 'name' => 'کیش'],
                ['id' => 406, 'state_id' =>  29, 'name' => 'بندر لنگه'],
                ['id' => 407, 'state_id' =>  29, 'name' => 'بستک'],
                ['id' => 408, 'state_id' =>  29, 'name' => 'حاجی آباد'],
                ['id' => 409, 'state_id' =>  29, 'name' => 'دهبارز'],
                ['id' => 410, 'state_id' =>  29, 'name' => 'انگهران'],
                ['id' => 411, 'state_id' =>  29, 'name' => 'میناب'],
                ['id' => 412, 'state_id' =>  29, 'name' => 'ابوموسی'],
                ['id' => 413, 'state_id' =>  29, 'name' => 'بندر جاسک'],
                ['id' => 414, 'state_id' =>  29, 'name' => 'تنب بزرگ'],
                ['id' => 415, 'state_id' =>  29, 'name' => 'بندر خمیر'],
                ['id' => 416, 'state_id' =>  29, 'name' => 'پارسیان'],
                ['id' => 417, 'state_id' =>  29, 'name' => 'قشم'],
                ['id' => 418, 'state_id' =>  30, 'name' => 'همدان'],
                ['id' => 419, 'state_id' =>  30, 'name' => 'ملایر'],
                ['id' => 420, 'state_id' =>  30, 'name' => 'تویسرکان'],
                ['id' => 421, 'state_id' =>  30, 'name' => 'نهاوند'],
                ['id' => 422, 'state_id' =>  30, 'name' => 'کبودر اهنگ'],
                ['id' => 423, 'state_id' =>  30, 'name' => 'رزن'],
                ['id' => 424, 'state_id' =>  30, 'name' => 'اسدآباد'],
                ['id' => 425, 'state_id' =>  30, 'name' => 'بهار'],
                ['id' => 426, 'state_id' =>  31, 'name' => 'یزد'],
                ['id' => 427, 'state_id' =>  31, 'name' => 'تفت'],
                ['id' => 428, 'state_id' =>  31, 'name' => 'اردکان'],
                ['id' => 429, 'state_id' =>  31, 'name' => 'ابرکوه'],
                ['id' => 430, 'state_id' =>  31, 'name' => 'میبد'],
                ['id' => 431, 'state_id' =>  31, 'name' => 'طبس'],
                ['id' => 432, 'state_id' =>  31, 'name' => 'بافق'],
                ['id' => 433, 'state_id' =>  31, 'name' => 'مهریز'],
                ['id' => 434, 'state_id' =>  31, 'name' => 'اشکذر'],
                ['id' => 435, 'state_id' =>  31, 'name' => 'هرات'],
                ['id' => 436, 'state_id' =>  31, 'name' => 'خضرآباد'],
                ['id' => 437, 'state_id' =>  31, 'name' => 'شاهدیه'],
                ['id' => 438, 'state_id' =>  31, 'name' => 'حمیدیه شهر'],
                ['id' => 439, 'state_id' =>  31, 'name' => 'سید میرزا'],
                ['id' => 440, 'state_id' => 31,  'name' => 'زارچ']
            ]
        );
    }
}

