<ul class="fa-icon-list" id="categorie_icon">
    <li class="d-inline-block h1"><i class="fa fa-address-book d-inline"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-address-card"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-adjust"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-align-center"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-align-justify"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-align-left"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-align-right"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-allergies"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-ambulance"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-american-sign-language-interpreting"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-anchor"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-angle-double-down"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-angle-double-left"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-angle-double-right"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-angle-double-up"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-angle-down"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-angle-left"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-angle-right"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-angle-up"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-archive"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-arrow-alt-circle-down"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-arrow-alt-circle-left"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-arrow-alt-circle-right"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-arrow-alt-circle-up"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-arrow-circle-down"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-arrow-circle-left"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-arrow-circle-right"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-arrow-circle-up"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-arrow-down"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-arrow-left"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-arrow-right"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-arrow-up"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-arrows-alt"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-arrows-alt-h"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-arrows-alt-v"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-assistive-listening-systems"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-asterisk"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-at"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-audio-description"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-backward"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-balance-scale"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-ban"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-band-aid"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-barcode"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-bars"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-baseball-ball"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-basketball-ball"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-bath"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-battery-empty"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-battery-full"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-battery-half"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-battery-quarter"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-battery-three-quarters"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-bed"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-beer"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-bell"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-bell-slash"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-bicycle"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-binoculars"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-birthday-cake"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-blind"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-bold"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-bolt"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-bomb"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-book"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-book-open"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-bookmark"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-bowling-ball"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-box"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-box-open"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-boxes"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-braille"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-briefcase"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-briefcase-medical"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-broadcast-tower"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-broom"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-bug"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-building"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-bullhorn"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-bullseye"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-burn"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-bus"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-calculator"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-calendar"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-calendar-alt"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-calendar-check"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-calendar-minus"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-calendar-plus"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-calendar-times"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-camera"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-camera-retro"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-capsules"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-car"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-caret-down"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-caret-left"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-caret-right"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-caret-square-down"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-caret-square-left"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-caret-square-right"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-caret-square-up"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-caret-up"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-cart-arrow-down"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-cart-plus"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-certificate"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-chalkboard"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-chalkboard-teacher"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-chart-area"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-chart-bar"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-chart-line"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-chart-pie"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-check"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-check-circle"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-check-square"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-chess"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-chess-bishop"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-chess-board"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-chess-king"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-chess-knight"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-chess-pawn"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-chess-queen"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-chess-rook"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-chevron-circle-down"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-chevron-circle-left"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-chevron-circle-right"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-chevron-circle-up"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-chevron-down"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-chevron-left"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-chevron-right"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-chevron-up"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-child"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-church"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-circle"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-circle-notch"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-clipboard"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-clipboard-check"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-clipboard-list"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-clock"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-clone"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-closed-captioning"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-cloud"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-cloud-download-alt"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-cloud-upload-alt"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-code"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-code-branch"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-coffee"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-cog"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-cogs"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-coins"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-columns"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-comment"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-comment-alt"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-comment-dots"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-comment-slash"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-comments"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-compact-disc"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-compass"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-compress"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-copy"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-copyright"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-couch"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-credit-card"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-crop"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-crow"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-crown"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-cube"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-cubes"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-cut"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-database"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-deaf"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-desktop"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-diagnoses"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-dice"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-dice-five"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-dice-four"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-dice-one"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-dice-six"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-dice-three"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-dice-two"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-crosshairs"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-blender"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-divide"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-dna"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-dollar-sign"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-dolly"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-dolly-flatbed"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-donate"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-door-closed"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-door-open"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-dot-circle"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-dove"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-download"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-edit"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-eject"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-ellipsis-h"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-ellipsis-v"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-envelope"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-envelope-open"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-envelope-square"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-equals"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-eraser"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-euro-sign"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-exclamation"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-exclamation-circle"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-exclamation-triangle"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-expand"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-expand-arrows-alt"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-external-link-alt"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-external-link-square-alt"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-eye"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-eye-dropper"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-eye-slash"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-fast-backward"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-fast-forward"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-fax"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-feather"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-female"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-fighter-jet"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-file"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-file-alt"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-file-archive"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-file-audio"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-file-code"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-file-excel"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-file-image"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-file-medical"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-file-medical-alt"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-file-pdf"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-file-powerpoint"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-file-video"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-file-word"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-film"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-filter"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-fire"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-fire-extinguisher"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-first-aid"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-flag"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-flag-checkered"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-futbol"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-flask"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-folder"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-folder-open"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-font"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-football-ball"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-forward"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-frog"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-frown"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-exchange-alt"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-dumbbell"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-gamepad"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-gas-pump"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-gavel"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-gem"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-genderless"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-gift"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-glass-martini"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-glasses"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-globe"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-golf-ball"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-graduation-cap"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-greater-than"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-greater-than-equal"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-hand-holding"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-hand-holding-heart"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-hand-holding-usd"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-hand-lizard"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-hand-paper"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-hand-peace"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-hand-point-down"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-hand-point-left"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-hand-point-right"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-hand-point-up"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-hand-pointer"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-hand-rock"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-hand-scissors"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-hand-spock"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-hands"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-hands-helping"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-handshake"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-hashtag"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-hdd"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-heading"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-headphones"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-heart"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-heartbeat"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-helicopter"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-history"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-hockey-puck"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-home"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-hospital"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-hospital-alt"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-hospital-symbol"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-hourglass"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-hourglass-end"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-hourglass-half"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-hourglass-start"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-i-cursor"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-id-badge"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-id-card"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-id-card-alt"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-image"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-images"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-inbox"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-indent"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-industry"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-infinity"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-info"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-info-circle"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-italic"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-key"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-keyboard"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-kiwi-bird"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-language"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-laptop"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-leaf"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-lemon"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-less-than"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-less-than-equal"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-level-down-alt"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-level-up-alt"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-life-ring"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-lightbulb"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-link"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-lira-sign"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-list"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-list-alt"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-list-ol"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-list-ul"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-location-arrow"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-lock"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-lock-open"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-long-arrow-alt-down"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-long-arrow-alt-left"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-long-arrow-alt-right"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-long-arrow-alt-up"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-low-vision"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-magic"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-magnet"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-male"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-map"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-map-marker"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-map-marker-alt"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-map-pin"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-map-signs"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-mars"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-mars-double"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-mars-stroke"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-mars-stroke-h"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-mars-stroke-v"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-medkit"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-meh"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-memory"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-microchip"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-microphone"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-microphone-alt"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-microphone-alt-slash"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-microphone-slash"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-minus"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-minus-circle"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-minus-square"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-mobile"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-mobile-alt"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-money-bill"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-money-bill-alt"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-money-bill-wave-alt"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-money-bill-wave"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-money-check"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-money-check-alt"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-moon"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-motorcycle"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-mouse-pointer"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-music"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-newspaper"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-not-equal"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-notes-medical"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-object-group"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-object-ungroup"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-outdent"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-paint-brush"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-palette"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-pallet"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-paper-plane"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-paperclip"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-parachute-box"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-paragraph"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-parking"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-paste"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-pause"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-pause-circle"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-paw"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-pen-square"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-pencil-alt"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-people-carry"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-percent"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-percentage"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-phone"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-phone-slash"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-phone-square"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-phone-volume"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-pills"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-plane"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-play"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-play-circle"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-plug"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-plus"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-plus-circle"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-plus-square"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-podcast"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-portrait"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-pound-sign"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-power-off"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-prescription-bottle"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-prescription-bottle-alt"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-print"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-procedures"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-project-diagram"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-puzzle-piece"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-qrcode"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-question"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-question-circle"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-quote-left"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-quote-right"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-random"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-receipt"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-recycle"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-redo"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-redo-alt"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-registered"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-reply"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-reply-all"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-retweet"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-ribbon"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-road"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-robot"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-rocket"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-rss"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-rss-square"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-ruble-sign"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-ruler"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-ruler-combined"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-ruler-horizontal"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-ruler-vertical"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-rupee-sign"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-save"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-school"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-screwdriver"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-search"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-search-minus"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-search-plus"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-server"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-share"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-share-alt"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-share-alt-square"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-share-square"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-shekel-sign"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-shield-alt"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-ship"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-shopping-bag"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-shopping-basket"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-shopping-cart"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-shower"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-sign"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-sign-in-alt"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-sign-language"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-sign-out-alt"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-signal"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-sitemap"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-skull"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-sliders-h"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-smile"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-smoking"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-smoking-ban"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-snowflake"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-sort"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-sort-alpha-down"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-sort-alpha-up"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-sort-amount-down"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-sort-amount-up"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-sort-down"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-sort-numeric-down"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-sort-numeric-up"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-sort-up"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-space-shuttle"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-spinner"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-square"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-square-full"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-star"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-star-half"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-step-backward"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-step-forward"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-stop"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-stop-circle"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-stopwatch"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-store"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-store-alt"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-stream"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-street-view"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-strikethrough"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-subscript"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-subway"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-suitcase"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-sun"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-superscript"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-sync"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-sync-alt"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-table"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-table-tennis"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-tablet"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-tablet-alt"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-tablets"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-tachometer-alt"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-tag"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-tags"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-tape"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-tasks"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-taxi"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-terminal"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-text-height"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-text-width"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-th"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-th-large"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-th-list"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-thermometer"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-thermometer-empty"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-thermometer-full"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-thermometer-half"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-thermometer-quarter"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-thermometer-three-quarters"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-thumbs-down"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-thumbs-up"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-ticket-alt"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-times"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-times-circle"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-tint"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-toggle-off"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-toggle-on"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-toolbox"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-train"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-trademark"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-transgender"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-transgender-alt"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-trash"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-trash-alt"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-tree"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-trophy"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-truck"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-truck-loading"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-truck-moving"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-tshirt"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-tty"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-tv"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-umbrella"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-underline"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-undo"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-undo-alt"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-universal-access"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-university"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-unlink"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-unlock"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-unlock-alt"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-upload"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-user"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-user-alt"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-user-alt-slash"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-user-astronaut"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-user-check"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-user-circle"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-user-clock"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-user-cog"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-user-edit"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-user-friends"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-user-graduate"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-user-lock"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-user-md"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-user-minus"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-user-ninja"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-user-plus"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-user-secret"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-user-shield"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-user-slash"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-user-tag"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-user-tie"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-user-times"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-users"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-users-cog"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-venus"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-venus-double"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-venus-mars"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-vial"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-vials"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-video"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-video-slash"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-volleyball-ball"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-volume-down"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-volume-off"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-volume-up"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-walking"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-wallet"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-warehouse"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-weight"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-wheelchair"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-wifi"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-window-close"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-window-maximize"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-window-minimize"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-window-restore"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-wine-glass"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-won-sign"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-wrench"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-x-ray"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-yen-sign"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-h-square"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-mercury"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-neuter"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-piggy-bank"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-poo"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-quidditch"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-seedling"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-shipping-fast"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-shoe-prints"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-stethoscope"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-stroopwafel"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-syringe"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-utensil-spoon"></i></li>
    <li class="d-inline-block h1"><i class="fa fa-utensils"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-accessible-icon"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-500px"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-accusoft"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-amazon"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-amazon-pay"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-apple"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-apple-pay"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-adn"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-adversal"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-affiliatetheme"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-algolia"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-amilia"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-android"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-angellist"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-angrycreative"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-angular"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-app-store"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-app-store-ios"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-apper"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-bandcamp"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-asymmetrik"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-audible"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-autoprefixer"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-avianex"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-aviato"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-aws"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-behance"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-behance-square"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-bitbucket"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-bity"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-black-tie"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-blackberry"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-blogger"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-blogger-b"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-buysellads"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-cc-amazon-pay"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-cc-amex"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-cc-apple-pay"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-cc-diners-club"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-cc-discover"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-bluetooth"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-bluetooth-b"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-bitcoin"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-bimobject"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-buromobelexperte"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-btc"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-cc-jcb"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-cc-mastercard"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-cc-paypal"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-cc-stripe"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-cc-visa"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-centercode"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-chrome"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-codepen"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-codiepie"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-connectdevelop"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-contao"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-cpanel"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-css3"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-css3-alt"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-cuttlefish"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-d-and-d"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-dashcube"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-deploydog"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-deskpro"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-deviantart"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-digg"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-creative-commons"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-creative-commons-by"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-creative-commons-nc"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-creative-commons-nc-eu"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-creative-commons-nc-jp"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-creative-commons-nd"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-creative-commons-pd"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-creative-commons-pd-alt"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-creative-commons-remix"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-creative-commons-sa"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-creative-commons-sampling"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-creative-commons-sampling-plus"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-creative-commons-share"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-cloudscale"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-cloudsmith"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-cloudversify"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-delicious"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-digital-ocean"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-discord"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-discourse"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-dochub"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-docker"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-draft2digital"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-dribbble"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-dribbble-square"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-dropbox"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-drupal"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-dyalog"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-earlybirds"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-ebay"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-edge"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-elementor"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-ember"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-empire"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-envira"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-erlang"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-ethereum"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-etsy"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-expeditedssl"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-facebook"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-facebook-f"></i></li>
    <li class="d-inline-block h1"><i class="fab d-inline fa-facebook-messenger"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-facebook-square"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-firefox"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-firstdraft"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-flickr"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-flipboard"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-fonticons"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-fonticons-fi"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-fort-awesome"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-fort-awesome-alt"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-forumbee"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-foursquare"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-free-code-camp"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-freebsd"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-first-order"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-first-order-alt"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-font-awesome"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-font-awesome-alt"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-font-awesome-flag"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-fulcrum"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-fly"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-galactic-republic"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-galactic-senate"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-github"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-github-alt"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-github-square"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-gitkraken"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-gitlab"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-gitter"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-glide"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-glide-g"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-gofore"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-goodreads"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-goodreads-g"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-google"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-google-drive"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-google-play"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-google-plus"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-google-plus-g"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-google-plus-square"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-google-wallet"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-gratipay"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-grav"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-gripfire"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-grunt"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-gulp"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-hacker-news"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-hacker-news-square"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-hire-a-helper"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-hooli"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-hotjar"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-html5"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-houzz"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-hubspot"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-imdb"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-instagram"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-internet-explorer"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-ioxhost"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-itunes"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-itunes-note"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-java"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-jedi-order"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-jenkins"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-joget"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-joomla"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-js"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-js-square"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-jsfiddle"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-keybase"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-keycdn"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-kickstarter"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-kickstarter-k"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-laravel"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-lastfm"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-lastfm-square"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-leanpub"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-less"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-linkedin"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-linkedin-in"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-linode"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-linux"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-lyft"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-magento"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-mastodon"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-maxcdn"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-medapps"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-medium"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-medium-m"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-microsoft"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-mixcloud"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-mizuni"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-modx"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-monero"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-napster"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-node-js"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-npm"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-ns8"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-nutritionix"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-odnoklassniki"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-odnoklassniki-square"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-old-republic"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-opencart"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-openid"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-opera"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-optin-monster"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-osi"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-page4"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-patreon"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-paypal"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-periscope"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-phabricator"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-phoenix-framework"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-phoenix-squadron"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-php"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-pied-piper"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-pied-piper-alt"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-pied-piper-hat"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-pied-piper-pp"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-pinterest"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-pinterest-p"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-pinterest-square"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-playstation"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-product-hunt"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-python"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-qq"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-quinscape"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-quora"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-r-project"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-ravelry"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-react"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-rebel"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-red-river"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-reddit"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-reddit-alien"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-reddit-square"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-rendact"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-renren"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-researchgate"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-rocketchat"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-rockrms"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-safari"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-sass"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-schlix"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-scribd"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-searchengin"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-sellcast"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-sellsy"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-servicestack"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-shirtsinbulk"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-simplybuilt"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-sistrix"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-sith"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-skype"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-slack"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-slack-hash"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-slideshare"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-snapchat"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-snapchat-ghost"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-snapchat-square"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-soundcloud"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-speakap"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-spotify"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-stack-exchange"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-stack-overflow"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-staylinked"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-steam"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-steam-symbol"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-steam-square"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-sticker-mule"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-strava"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-stripe"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-stripe-s"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-studiovinari"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-teamspeak"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-telegram"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-telegram-plane"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-tencent-weibo"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-themeisle"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-trade-federation"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-trello"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-tripadvisor"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-tumblr"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-tumblr-square"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-twitch"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-twitter"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-twitter-square"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-typo3"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-uber"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-uikit"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-uniregistry"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-untappd"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-ussunnah"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-vaadin"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-viacoin"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-viadeo"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-viadeo-square"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-viber"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-vimeo"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-vimeo-square"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-vimeo-v"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-vine"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-vk"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-vnv"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-vuejs"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-weibo"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-weixin"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-whatsapp"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-whatsapp-square"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-whmcs"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-wikipedia-w"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-windows"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-wolf-pack-battalion"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-wordpress"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-wordpress-simple"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-wpbeginner"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-wpexplorer"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-wpforms"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-xbox"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-xing"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-xing-square"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-y-combinator"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-yahoo"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-yandex"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-yandex-international"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-yelp"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-yoast"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-youtube"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-youtube-square"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-get-pocket"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-gg"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-gg-circle"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-git"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-git-square"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-hips"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-line"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-korvue"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-mandalorian"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-medrt"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-meetup"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-mix"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-nintendo-switch"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-node"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-pagelines"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-palfed"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-pushed"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-readme"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-replyd"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-resolving"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-skyatlas"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-stumbleupon"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-stumbleupon-circle"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-supple"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-superpowers"></i></li>
    <li class="d-inline-block h1"><i class="fab fa-usb"></i></li>
</ul>
